[package]
name = "hammer-plugin-tun"
version.workspace = true
edition.workspace = true
publish.workspace = true

[lib]
name = "hammer_plugin_tun"
crate-type = ["cdylib", "rlib"]

[dependencies]
hammer-core = { path = "../../../hammer-core" }
hammer-infra = { path = "../../../hammer-infra" }
hammer-runtime = { path = "../../../hammer-runtime", default-features = false }
hammer-service = { path = "../../../hammer-service", default-features = false }
hammer-component-macros = { path = "../../../hammer-component-macros" }
libc = { workspace = true }
serde = { workspace = true }
linkme = { workspace = true }
tracing = { workspace = true }
