[workspace]
resolver = "3"
members = [
    "crates/hammer-infra",
    "crates/hammer-core",
    "crates/hammer-component-macros",
    "crates/hammer-runtime",
    "crates/hammer-service",
    "crates/hammer-plugins/ip",
    "crates/hammer-plugins/transport/tcp",
    "crates/hammer-plugins/transport/udp",
    "crates/hammer-plugins/app-session/quic",
    "crates/hammer-plugins/app-session/tls",
    "crates/hammer-plugins/app-session/http",
    "crates/hammer-app",
    "crates/hammer-stats",
    "crates/hammer-ipc",
    "crates/hammer",
    "crates/hammerctl",
    "third_party/quinn/quinn-proto",
]
exclude = [
    "third_party/allocator-api2",
    "third_party/io-uring",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
publish = false

[profile.release]
lto = "thin"
codegen-units = 16
opt-level = 3

[profile.release-perf]
inherits = "release"
debug = "line-tables-only"
strip = "none"
lto = false

[workspace.dependencies]
abi_stable = "0.11.3"
tokio = { version = "1.52", features = ["rt-multi-thread", "sync", "macros", "time", "io-util", "net"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_path_to_error = "0.1"
toml = "1.1"
url = { version = "2.5", features = ["serde"] }
nom = "8"
thiserror = "2.0"
async-trait = "0.1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", default-features = false, features = ["registry", "std", "fmt", "env-filter"] }
metrics = "0.24"
metrics-derive = "0.1"
humantime-serde = "1.1"
byte-unit = { version = "5.2.5", features = ["serde"] }
parse-display = "0.11.0"
procfs = { version = "0.18.0", default-features = false }
serde_with = { version = "3.21.0", default-features = false, features = ["macros"] }
bytes = "1.11"
bitflags = "2.10"
crossbeam-queue = "0.3"
etherparse = "0.20.1"
arc-swap = "1"
smoltcp = { version = "0.12", default-features = false, features = ["std", "alloc", "log", "medium-ip", "proto-ipv4", "socket-tcp", "socket-tcp-reno", "socket-tcp-cubic"] }
rand = "0.8"
socket2 = "0.6"
lru = { version = "0.18", default-features = false }
ipnet = { version = "2", features = ["serde"] }
libc = "0.2"
memmap2 = "0.9"
core_affinity = "0.8"
thread-priority = "1.2"
rustc-hash = "2"
indoc = "2.0"
rcgen = "0.14"
rustls = { version = "=0.23.31", default-features = false, features = ["ring", "std"] }
quinn-proto = { path = "third_party/quinn/quinn-proto", default-features = false, features = ["rustls"] }
criterion = { version = "0.5", default-features = false, features = ["plotters", "cargo_bench_support"] }
linkme = "0.3"
petgraph = "0.6"
prost = "0.14.4"
clap = "4"
bincode = "1"
libmimalloc-sys = { version = "0.1.49", features = ["arena", "extended"] }
talc = { version = "5.0.4", default-features = false }
spinning_top = "0.3"
io-uring = "0.7.13"
semver = "1"
libloading = "0.8"
object = "0.38"

[patch.crates-io]
io-uring = { path = "third_party/io-uring" }
