[package]
name = "hammer-app"
version.workspace = true
edition.workspace = true
publish.workspace = true

[lib]
name = "hammer_app"

[dependencies]
hammer-adapter = { path = "../hammer-adapter" }
hammer-core = { path = "../hammer-core" }
hammer-infra = { path = "../hammer-infra" }
hammer-runtime = { path = "../hammer-runtime" }
libc = { workspace = true }
tokio = { workspace = true }
