[package]
name = "hammer-core"
version.workspace = true
edition.workspace = true
publish.workspace = true

[lib]
name = "hammer_core"
crate-type = ["dylib", "rlib"]

[features]
default = []

[dependencies]
hammer-infra = { path = "../hammer-infra" }
thiserror = { workspace = true }
spinning_top = { workspace = true }
