[package]
name = "hammer-core"
version.workspace = true
edition.workspace = true
publish.workspace = true

[lib]
name = "hammer_core"
crate-type = ["dylib", "rlib"]

[features]
default = []

[dependencies]
zerocopy = { version = "0.8.48", features = ["derive"] }
abi_stable = { workspace = true }
hammer-infra = { path = "../hammer-infra" }
thiserror = { workspace = true }
spinning_top = { workspace = true }

[dev-dependencies]
hammer-component-macros = { path = "../hammer-component-macros" }
