[package]
name = "hammer"
version = "0.1.0"
edition = "2024"
publish = false

[[bin]]
name = "hammer"
path = "src/main.rs"

[dependencies]
hammer-runtime = { path = "../hammer-runtime" }
hammer-ipc = { path = "../hammer-ipc" }
hammer-service = { path = "../hammer-service" }
hammer-core = { path = "../hammer-core" }
hammer-component-macros = { path = "../hammer-component-macros" }
clap = { workspace = true, features = ["derive"] }
tokio = { workspace = true }
toml = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
bincode = { workspace = true }
linkme = { workspace = true }
