[package]
name = "hammer"
version = "0.1.0"
edition = "2024"
publish = false

[[bin]]
name = "hammer"
path = "src/main.rs"

[[example]]
name = "tun_tcp_echo"
path = "../../examples/tun/tcp_echo.rs"

[[example]]
name = "tun_tls_echo"
path = "../../examples/tun/tls_echo.rs"

[dependencies]
hammer-runtime = { path = "../hammer-runtime" }
hammer-infra = { path = "../hammer-infra" }
hammer-service = { path = "../hammer-service" }
hammer-core = { path = "../hammer-core" }
hammer-component-macros = { path = "../hammer-component-macros" }
clap = { workspace = true, features = ["derive"] }
tokio = { workspace = true }
toml = { workspace = true }
serde = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
libloading = { workspace = true }
thiserror = { workspace = true }

[target.'cfg(target_os = "linux")'.dependencies]
core_affinity = { workspace = true }

[dev-dependencies]
hammer-app = { path = "../hammer-app" }
hammer-plugin-ip = { path = "../hammer-plugins/ip" }
hammer-plugin-tcp = { path = "../hammer-plugins/transport/tcp" }
hammer-plugin-udp = { path = "../hammer-plugins/transport/udp" }
hammer-plugin-tun = { path = "../hammer-plugins/device/tun" }
libc = { workspace = true }
ipnet = { workspace = true }
prost = { workspace = true }
