[package]
name = "hammer-service"
version.workspace = true
edition.workspace = true
publish.workspace = true

[lib]
name = "hammer_service"

[[example]]
name = "host-ping"
path = "examples/tun/host_ping.rs"
required-features = ["inbound-tun"]

[features]
default = [
    "inbound-tun",
    "outbound-block",
    "probe",
]
probe = ["hammer-runtime/probe"]
inbound-tun = ["dep:libc"]
outbound-block = ["hammer-runtime/outbound-block"]
endpoint = ["hammer-runtime/endpoint"]
endpoint-wireguard = ["hammer-runtime/endpoint-wireguard"]
endpoint-amneziawg = ["hammer-runtime/endpoint-amneziawg"]

[dependencies]
arc-swap = { workspace = true }
async-trait = { workspace = true }
bitflags = "2.10"
bytes = { workspace = true, optional = true }
hammer-core = { path = "../hammer-core" }
hammer-control = { path = "../hammer-control" }
hammer-adapter = { path = "../hammer-adapter" }
hammer-infra = { path = "../hammer-infra" }
hammer-component-macros = { path = "../hammer-component-macros" }
hammer-runtime = { path = "../hammer-runtime", default-features = false }
ipnet = { workspace = true }
nom = { workspace = true }
etherparse = { workspace = true }
tokio = { workspace = true, features = ["signal"] }
tracing = { workspace = true }
libc = { workspace = true, optional = true }
smoltcp = { workspace = true }

[dev-dependencies]
