[package]
name = "hammer-ipc"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
hammer-core = { path = "../hammer-core" }
hammer-infra = { path = "../hammer-infra" }
hammer-runtime = { path = "../hammer-runtime" }
serde = { workspace = true, features = ["derive"] }
bincode = { workspace = true }
libc = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["net", "io-util"] }
linkme = { workspace = true }
