[package]
name = "hammer-ipc"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
hammer-stats = { path = "../hammer-stats" }
libc = { workspace = true }
memmap2 = { workspace = true }
prost = { workspace = true }
socket2 = { workspace = true, features = ["all"] }
thiserror = { workspace = true }
