[package]
name = "hammerctl"
version = "0.1.0"
edition = "2024"
publish = false

[[bin]]
name = "hammerctl"
path = "src/main.rs"

[dependencies]
hammer-ipc = { path = "../hammer-ipc" }
hammer-infra = { path = "../hammer-infra" }
clap = { workspace = true, features = ["derive"] }
bincode = { workspace = true }
tokio = { workspace = true, features = ["net", "rt"] }
hex = "0.4"