[package]
name = "hammer-stats"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
hammer-component-macros = { path = "../hammer-component-macros" }
hammer-core = { path = "../hammer-core" }
hammer-infra = { path = "../hammer-infra" }
libc = { workspace = true }
socket2 = { workspace = true, features = ["all"] }
