[package]
name = "hammer-infra"
version.workspace = true
edition.workspace = true
publish.workspace = true

[lib]
name = "hammer_infra"
crate-type = ["dylib", "rlib"]

[dependencies]
bytes = { workspace = true }
byte-unit = { workspace = true }
libc = { workspace = true }
libmimalloc-sys = { workspace = true }
parse-display = { workspace = true }
serde = { workspace = true }
serde_with = { workspace = true }
spinning_top = { workspace = true }
talc = { workspace = true }
thiserror = { workspace = true }

[target.'cfg(target_os = "linux")'.dependencies]
procfs = { workspace = true }
