[package]
name = "hammer-infra"
version.workspace = true
edition.workspace = true
publish.workspace = true

[lib]
name = "hammer_infra"

[dependencies]
allocator-api2 = { workspace = true }
crossbeam-utils = { workspace = true }
libc = { workspace = true }
mimalloc = { workspace = true }
spinning_top = { workspace = true }
talc = { workspace = true }
