[package]
name = "hammer-plugin-ip"
version.workspace = true
edition.workspace = true
publish.workspace = true

[lib]
name = "hammer_plugin_ip"
crate-type = ["dylib", "rlib"]

[dependencies]
abi_stable = { workspace = true }
arc-swap = { workspace = true }
bitflags = { workspace = true }
hammer-core = { path = "../../../hammer-core" }
hammer-infra = { path = "../../../hammer-infra" }
hammer-runtime = { path = "../../../hammer-runtime", default-features = false }
hammer-service = { path = "../../../hammer-service", default-features = false }
hammer-component-macros = { path = "../../../hammer-component-macros" }
linkme = { workspace = true }
ipnet = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
toml = { workspace = true }
humantime-serde = { workspace = true }
