[package]
name = "hammer-vcl"
version.workspace = true
edition.workspace = true
publish.workspace = true

[lib]
name = "hammer_vcl"

[dependencies]
hammer-app = { path = "../hammer-app" }
hammer-runtime = { path = "../hammer-runtime" }
thiserror = { workspace = true }

[dev-dependencies]
hammer-infra = { path = "../hammer-infra" }
libc = { workspace = true }
tokio = { workspace = true }
