//! Platform-specific plugin path and registration-symbol access.
//!
//! [`crate::plugin::PluginMain`] is the public loading and lifetime authority;
//! this module only contains the unsafe `dlopen` boundary helpers it uses.

use std::path::{Path, PathBuf};
#[cfg(unix)]
use std::ptr::NonNull;

#[cfg(not(unix))]
use libloading::Library;

use crate::PluginRegistration;

/// Platform cdylib file name for a plugin root, e.g. `libhammer_plugin_tun.dylib`.
pub fn plugin_cdylib_filename(plugin_name: &str) -> String {
    libloading::library_filename(format!("hammer_plugin_{plugin_name}"))
        .to_string_lossy()
        .into_owned()
}

pub fn plugin_cdylib_path(dir: &Path, plugin_name: &str) -> PathBuf {
    dir.join(plugin_cdylib_filename(plugin_name))
}

/// Open a startup plugin without permitting its image to be unmapped.
///
/// Rust DSOs contain allocator TLS, registration statics, and Drop glue whose
/// process-wide teardown order cannot be proven safe at `PluginMain` drop.
/// `RTLD_NODELETE` retains the image until process exit. `PluginMain` also
/// retains the handle itself because even calling `dlclose` is outside the
/// proven startup lifecycle. Runtime plugin unload requires a separate drain
/// and teardown protocol.
pub(crate) struct PluginLibrary {
    #[cfg(unix)]
    handle: NonNull<libc::c_void>,
    #[cfg(not(unix))]
    library: &'static Library,
}

// SAFETY: POSIX permits a successful dlopen handle to be used by dlsym from
// multiple threads. Hammer never closes this process-lifetime handle, and the
// exported registration is initialized through a thread-safe OnceLock.
#[cfg(unix)]
unsafe impl Send for PluginLibrary {}

// SAFETY: see the Send implementation. Symbol lookup does not mutate the
// handle, and PluginMain publishes the library only after validation.
#[cfg(unix)]
unsafe impl Sync for PluginLibrary {}

pub(crate) fn open_plugin_library(path: &Path) -> Result<PluginLibrary, libloading::Error> {
    #[cfg(unix)]
    {
        use libloading::os::unix::{Library as UnixLibrary, RTLD_LOCAL, RTLD_NOW};

        // SAFETY: loading executes plugin initializers. The caller validates
        // the exported registration before using it, retains the returned
        // handle for every imported pointer, and RTLD_NODELETE prevents unsafe
        // termination routines from running during ordinary handle teardown.
        let library =
            unsafe { UnixLibrary::open(Some(path), RTLD_NOW | RTLD_LOCAL | libc::RTLD_NODELETE) }?;
        let handle = NonNull::new(library.into_raw())
            .expect("a successfully opened plugin library has a non-null handle");
        Ok(PluginLibrary { handle })
    }

    #[cfg(not(unix))]
    {
        // SAFETY: non-Unix targets do not currently provide Hammer plugins.
        // This fallback preserves compilation until that platform defines an
        // equivalent process-lifetime image policy.
        let library = unsafe { Library::new(path) }?;
        Ok(PluginLibrary {
            library: Box::leak(Box::new(library)),
        })
    }
}

/// Resolve the daemon plugin directory.
///
/// VPP has `plugin_path`; Hammer accepts `HAMMER_PLUGIN_DIR` and otherwise
/// loads libraries placed beside the daemon executable.
pub fn configured_plugin_path() -> Result<PathBuf, String> {
    if let Some(path) = std::env::var_os("HAMMER_PLUGIN_DIR") {
        return Ok(PathBuf::from(path));
    }
    let executable = std::env::current_exe().map_err(|error| error.to_string())?;
    executable.parent().map(Path::to_path_buf).ok_or_else(|| {
        format!(
            "daemon executable `{}` has no parent directory",
            executable.display()
        )
    })
}

/// Read the single registration export while `library` remains held.
pub(crate) fn read_plugin_registration(
    library: &PluginLibrary,
) -> Result<&PluginRegistration, String> {
    type RegistrationFn = unsafe extern "C" fn() -> *const PluginRegistration;

    #[cfg(unix)]
    let pointer = {
        use libloading::os::unix::Library as UnixLibrary;

        // SAFETY: `handle` came from `UnixLibrary::into_raw` and remains owned
        // by this PluginLibrary. The temporary owner is converted back into
        // the same handle below before it can run Drop.
        let temporary = unsafe { UnixLibrary::from_raw(library.handle.as_ptr()) };
        let result = {
            // SAFETY: the symbol name and C signature are generated by the
            // `declare_plugin!` contract. The Symbol is dropped before the
            // temporary library is converted back into its process handle.
            match unsafe { temporary.get::<RegistrationFn>(b"hammer_plugin_registration\0") } {
                Ok(symbol) => {
                    // SAFETY: generated registration functions initialize and
                    // return a DSO-owned OnceLock and never unwind.
                    Ok(unsafe { symbol() })
                }
                Err(error) => Err(error.to_string()),
            }
        };
        let handle = temporary.into_raw();
        debug_assert_eq!(handle, library.handle.as_ptr());
        result?
    };

    #[cfg(not(unix))]
    let pointer = {
        // SAFETY: the symbol name and C signature are generated by the
        // `declare_plugin!` contract, and the process-lifetime library remains
        // loaded while the symbol is called.
        let symbol = unsafe {
            library
                .library
                .get::<RegistrationFn>(b"hammer_plugin_registration\0")
        }
        .map_err(|error| error.to_string())?;
        // SAFETY: generated registration functions initialize and return a
        // DSO-owned OnceLock and never unwind.
        unsafe { symbol() }
    };

    if pointer.is_null() {
        return Err("hammer_plugin_registration returned null".into());
    }
    // SAFETY: the registration is DSO-static and the reference lifetime is
    // tied to the borrowed library handle retained by `PluginMain`.
    Ok(unsafe { &*pointer })
}

/// Workspace `target/{debug,release}` directory for integration tests.
pub fn workspace_target_dir() -> PathBuf {
    let profile = if cfg!(debug_assertions) {
        "debug"
    } else {
        "release"
    };
    if let Ok(dir) = std::env::var("CARGO_TARGET_DIR") {
        return PathBuf::from(dir).join(profile);
    }
    let mut dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    dir.pop();
    dir.pop();
    dir.join("target").join(profile)
}

pub fn built_plugin_cdylib_path(plugin_name: &str) -> PathBuf {
    let target = workspace_target_dir();
    let primary = plugin_cdylib_path(&target, plugin_name);
    if primary.is_file() {
        return primary;
    }
    plugin_cdylib_path(&target.join("deps"), plugin_name)
}

pub fn built_plugin_path() -> PathBuf {
    let target = workspace_target_dir();
    if plugin_cdylib_path(&target, "tun").is_file() {
        target
    } else {
        target.join("deps")
    }
}
