//! Platform-specific plugin path and registration-symbol access.
//!
//! [`crate::plugin::PluginMain`] is the public loading and lifetime authority;
//! this module only contains the unsafe `dlopen` boundary helpers it uses.

use std::path::{Path, PathBuf};

use libloading::Library;

use crate::PluginRegistration;

/// Platform cdylib file name for a plugin root, e.g. `libhammer_plugin_tun.dylib`.
pub fn plugin_cdylib_filename(plugin_name: &str) -> String {
    libloading::library_filename(format!("hammer_plugin_{plugin_name}"))
        .to_string_lossy()
        .into_owned()
}

pub fn plugin_cdylib_path(dir: &Path, plugin_name: &str) -> PathBuf {
    dir.join(plugin_cdylib_filename(plugin_name))
}

/// Resolve the daemon plugin directory.
///
/// VPP has `plugin_path`; Hammer accepts `HAMMER_PLUGIN_DIR` and otherwise
/// loads libraries placed beside the daemon executable.
pub fn configured_plugin_path() -> Result<PathBuf, String> {
    if let Some(path) = std::env::var_os("HAMMER_PLUGIN_DIR") {
        return Ok(PathBuf::from(path));
    }
    let executable = std::env::current_exe().map_err(|error| error.to_string())?;
    executable.parent().map(Path::to_path_buf).ok_or_else(|| {
        format!(
            "daemon executable `{}` has no parent directory",
            executable.display()
        )
    })
}

/// Read the single registration export while `library` remains held.
pub(crate) fn read_plugin_registration(library: &Library) -> Result<&PluginRegistration, String> {
    type RegistrationFn = unsafe extern "C" fn() -> *const PluginRegistration;
    // SAFETY: the symbol name and C signature are the contract generated by
    // `declare_plugin!`; the returned `Symbol` cannot outlive `library`.
    let symbol = unsafe { library.get::<RegistrationFn>(b"hammer_plugin_registration\0") }
        .map_err(|error| error.to_string())?;
    // SAFETY: generated registration functions return a DSO-static metadata
    // record and never unwind.
    let pointer = unsafe { symbol() };
    if pointer.is_null() {
        return Err("hammer_plugin_registration returned null".into());
    }
    // SAFETY: the registration is DSO-static and the reference lifetime is
    // tied to the borrowed library handle retained by `PluginMain`.
    Ok(unsafe { &*pointer })
}

/// Workspace `target/{debug,release}` directory for integration tests.
pub fn workspace_target_dir() -> PathBuf {
    let profile = if cfg!(debug_assertions) {
        "debug"
    } else {
        "release"
    };
    if let Ok(dir) = std::env::var("CARGO_TARGET_DIR") {
        return PathBuf::from(dir).join(profile);
    }
    let mut dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    dir.pop();
    dir.pop();
    dir.join("target").join(profile)
}

pub fn built_plugin_cdylib_path(plugin_name: &str) -> PathBuf {
    let target = workspace_target_dir();
    let dependency = plugin_cdylib_path(&target.join("deps"), plugin_name);
    if dependency.is_file() {
        return dependency;
    }
    plugin_cdylib_path(&target, plugin_name)
}

pub fn built_plugin_path() -> PathBuf {
    workspace_target_dir().join("deps")
}
