use core::mem;
use std::fmt;

#[derive(Clone, Copy)]
#[repr(C, align(8))]
pub(super) union PrimaryOpaque {
    words64: [u64; 5],
    words32: [u32; 10],
    bytes: [u8; 40],
}

pub const PRIMARY_OPAQUE_BYTES: usize = mem::size_of::<PrimaryOpaque>();
pub const PRIMARY_OPAQUE_ALIGN: usize = mem::align_of::<PrimaryOpaque>();

impl Default for PrimaryOpaque {
    fn default() -> Self {
        Self { words64: [0; 5] }
    }
}

impl fmt::Debug for PrimaryOpaque {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        let words64 = unsafe { self.words64 };
        f.debug_struct("PrimaryOpaque")
            .field("words64", &words64)
            .finish()
    }
}

#[derive(Clone, Copy)]
#[repr(C, align(8))]
pub(super) union SecondaryOpaque {
    words64: [u64; 7],
    words32: [u32; 14],
    bytes: [u8; 56],
}

impl Default for SecondaryOpaque {
    fn default() -> Self {
        Self { words64: [0; 7] }
    }
}

impl fmt::Debug for SecondaryOpaque {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        let words64 = unsafe { self.words64 };
        f.debug_struct("SecondaryOpaque")
            .field("words64", &words64)
            .finish()
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[doc(hidden)]
pub enum BufferOpaqueRegion {
    Primary,
    Secondary,
}

/// Fixed-layout contract generated by `#[buffer_opaque]`.
///
/// # Safety
/// Implementors must fit the selected region and accept every initialized bit
/// pattern, including zero, and contain no padding that assignment could leave
/// uninitialized. They must contain no references or interior mutable
/// state. Returned references must borrow the selected region of the supplied
/// Buffer without extending its lifetime.
#[doc(hidden)]
pub unsafe trait BufferOpaque:
    Copy + zerocopy::FromBytes + zerocopy::IntoBytes + zerocopy::Immutable
{
    const REGION: BufferOpaqueRegion;
    fn borrow(buffer: &super::Buffer) -> &Self;
    fn borrow_mut(buffer: &mut super::Buffer) -> &mut Self;
}

#[macro_export]
macro_rules! buffer_opaque {
    ($buffer:expr => $type:ty) => {
        <$type as $crate::data_plane::BufferOpaque>::borrow($buffer)
    };
    (mut $buffer:expr => $type:ty) => {
        <$type as $crate::data_plane::BufferOpaque>::borrow_mut($buffer)
    };
}

impl super::Buffer {
    #[doc(hidden)]
    #[inline(always)]
    pub fn primary_opaque<T: BufferOpaque>(&self) -> &T {
        const {
            assert!(matches!(T::REGION, BufferOpaqueRegion::Primary));
            assert!(mem::size_of::<T>() <= 40);
            assert!(mem::align_of::<T>() <= 8);
        }
        // SAFETY: BufferOpaque guarantees initialized, padding-free, all-bit-valid
        // storage. The checked region alignment and size contain T, and the
        // returned reference retains the Buffer borrow's lifetime and exclusivity.
        unsafe { &*(&self.cacheline0.opaque as *const _ as *const T) }
    }
    #[doc(hidden)]
    #[inline(always)]
    pub fn primary_opaque_mut<T: BufferOpaque>(&mut self) -> &mut T {
        const {
            assert!(matches!(T::REGION, BufferOpaqueRegion::Primary));
            assert!(mem::size_of::<T>() <= 40);
            assert!(mem::align_of::<T>() <= 8);
        }
        // SAFETY: BufferOpaque guarantees initialized, padding-free, all-bit-valid
        // storage. The checked region alignment and size contain T, and the
        // returned reference retains the Buffer borrow's lifetime and exclusivity.
        unsafe { &mut *(&mut self.cacheline0.opaque as *mut _ as *mut T) }
    }
    #[doc(hidden)]
    #[inline(always)]
    pub fn secondary_opaque<T: BufferOpaque>(&self) -> &T {
        const {
            assert!(matches!(T::REGION, BufferOpaqueRegion::Secondary));
            assert!(mem::size_of::<T>() <= 56);
            assert!(mem::align_of::<T>() <= 8);
        }
        // SAFETY: BufferOpaque guarantees initialized, padding-free, all-bit-valid
        // storage. The checked region alignment and size contain T, and the
        // returned reference retains the Buffer borrow's lifetime and exclusivity.
        unsafe { &*(&self.opaque2 as *const _ as *const T) }
    }
    #[doc(hidden)]
    #[inline(always)]
    pub fn secondary_opaque_mut<T: BufferOpaque>(&mut self) -> &mut T {
        const {
            assert!(matches!(T::REGION, BufferOpaqueRegion::Secondary));
            assert!(mem::size_of::<T>() <= 56);
            assert!(mem::align_of::<T>() <= 8);
        }
        // SAFETY: BufferOpaque guarantees initialized, padding-free, all-bit-valid
        // storage. The checked region alignment and size contain T, and the
        // returned reference retains the Buffer borrow's lifetime and exclusivity.
        unsafe { &mut *(&mut self.opaque2 as *mut _ as *mut T) }
    }
}

#[cfg(test)]
pub(super) mod tests {
    use crate::buffer::BufferMain;
    use crate::error::DataPlaneResult;

    #[hammer_component_macros::buffer_opaque(primary)]
    #[derive(Clone, Copy)]
    struct PacketMetadata {
        words: [u64; 5],
    }

    #[hammer_component_macros::buffer_opaque(secondary)]
    #[derive(Clone, Copy)]
    struct PacketSecondaryMetadata {
        words: [u64; 7],
    }

    // Derived from vlib/buffer_funcs.h: vlib_buffer_copy metadata copies and
    // vlib_buffer_pool_put template restoration; no standalone upstream opaque test.
    pub(in crate::buffer) fn metadata_copy_and_pool_recycle_preserve_secondary_storage(
        buffers: &BufferMain,
    ) -> DataPlaneResult<()> {
        let mut caches = buffers.borrow_worker_caches(1);
        let mut index = 0;
        assert_eq!(
            buffers.alloc_from_pool(&mut caches, core::slice::from_mut(&mut index), 0),
            1
        );
        {
            // Ownership: this test retains the segment and ends this borrow before freeing it.
            let buffer = buffers.buffer_mut(&mut caches, index);
            let address = std::ptr::from_ref(&*buffer).addr();
            let primary = crate::buffer_opaque!(mut buffer => PacketMetadata);
            assert_eq!(std::ptr::from_ref(primary).addr(), address + 24);
            primary.words = [0x0123_4567_89ab_cdef; 5];
            let secondary = crate::buffer_opaque!(mut buffer => PacketSecondaryMetadata);
            assert_eq!(std::ptr::from_ref(secondary).addr(), address + 72);
            secondary.words = [0xfedc_ba98_7654_3210; 7];
            buffer.put_uninit(4).copy_from_slice(&[17, 19, 23, 29]);
            buffer.push_uninit(2).copy_from_slice(&[11, 13]);
            buffer.set_trace_handle(7);
        }
        let copied = buffers.copy_no_chain(&mut caches, index).unwrap();
        {
            // Ownership: this test retains the segment and ends this borrow before freeing it.
            let buffer = buffers.buffer(&caches, copied);
            assert_eq!(buffer.current_data_offset(), -2);
            assert_eq!(buffer.current(), &[11, 13, 17, 19, 23, 29]);
            assert_eq!(buffer.trace_handle(), None);
            assert_eq!(
                crate::buffer_opaque!(&buffer => PacketMetadata).words,
                [0x0123_4567_89ab_cdef; 5]
            );
            assert_eq!(
                crate::buffer_opaque!(&buffer => PacketSecondaryMetadata).words,
                [0xfedc_ba98_7654_3210; 7]
            );
        }
        {
            // Ownership: the source remains owned and is distinct from the copy.
            let buffer = buffers.buffer_mut(&mut caches, index);
            assert_eq!(buffer.trace_handle(), Some(7));
            buffer.current_mut()[0] = 31;
        }
        // Ownership: both indices remain allocated; no mutation overlaps this borrow.
        assert_eq!(buffers.buffer(&caches, copied).current()[0], 11);
        buffers.free_buffers(&mut caches, &[index], true, |_| {});
        let mut recycled = 0;
        assert_eq!(
            buffers.alloc_from_pool(&mut caches, core::slice::from_mut(&mut recycled), 0),
            1
        );
        assert_eq!(recycled, index);
        {
            // Ownership: this test retains the segment and ends this borrow before freeing it.
            let buffer = buffers.buffer(&caches, recycled);
            assert_eq!(
                crate::buffer_opaque!(&buffer => PacketMetadata).words,
                [0; 5]
            );
            assert_eq!(
                crate::buffer_opaque!(&buffer => PacketSecondaryMetadata).words,
                [0xfedc_ba98_7654_3210; 7]
            );
        }
        buffers.free_buffers(&mut caches, &[copied], true, |_| {});
        buffers.free_buffers(&mut caches, &[recycled], true, |_| {});
        Ok(())
    }
}
