[package]
name = "hammer-adapter"
version.workspace = true
edition.workspace = true
publish.workspace = true

[lib]
name = "hammer_adapter"

[dependencies]
hammer-core = { path = "../hammer-core" }
async-trait = { workspace = true }
hickory-proto = { workspace = true }
tokio = { workspace = true }
once_cell = { workspace = true }
